language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- npm install -g bower grunt-cli
- bower install
services: mongodb
deploy:
  api_key:
    secure: MVDdrVJOCS/ekTkWyGXPezgbtO0bcqjqyhlpWa5QModsKnRPM8Z6ruZxLJlZuGzMdW4tCh/MLXWggvIow+N44iQr/NJvkZSBRmontuvXIUcD6+mGnuN3uaCHo6EGr8QFCoEQESH7MiTHvc/9ryRb6LBQA47tZgHr+t++rlw1DiA=
